# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

service: lfx-security-ossf-scanner
frameworkVersion: '^2.57.0'
variablesResolutionMode: 20210326

package:
  # Exclude all first - selectively add in lambda functions
  # Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
  # More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
  patterns:
    - '!auth/**'
    - '!bin/*'
    - '!dev.sh'
    - '!docs/**'
    - '!helpers/**'
    - '!Makefile'
    - '!.env/**'
    - '!.venv/**'
    - '!.git*'
    - '!.git/**'
    - '!.vscode/**'
    - '!.pylintrc'
    - '!node_modules/**'
    - '!package-lock.json'
    - '!yarn.lock'
    - '.serverless-wsgi'
    - '*.py'

custom:
  # Config for serverless-prune-plugin - remove all but the 10 most recent
  # versions to avoid the "Code storage limit exceeded" error
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: python3.9
  stage: ${env:STAGE}
  region: us-east-2
  timeout: 900 # 15 minutes
  logRetentionInDays: 14
  lambdaHashingVersion: '20201221' # Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release. Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"

  iam:
    role:
      # Alongside provider.iam.role.statements managed policies can also be added to this service-wide Role
      # These will also be merged into the generated IAM Role
      managedPolicies:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:*
          Resource: "*"
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"

  environment:
    STAGE: ${sls:stage}
    HOME: /tmp
    REGION: us-east-2
    # The Auth0 Configuration details
    AUTH0_PLATFORM_URL: ${env:AUTH0_PLATFORM_URL}
    AUTH0_PLATFORM_CLIENT_ID: ${env:AUTH0_PLATFORM_CLIENT_ID}
    AUTH0_PLATFORM_CLIENT_SECRET: ${env:AUTH0_PLATFORM_CLIENT_SECRET}
    AUTH0_PLATFORM_AUDIENCE: ${env:AUTH0_PLATFORM_AUDIENCE}
    # Logging format, text or json
    LOG_FORMAT: json

  stackTags:
    Name: ${self:service}
    stage: ${sls:stage}
    Project: "LFX Security"
    Product: "LFX Security"
    ManagedBy: "Serverless CloudFormation"
    SericeType: "Product"
    Service: ${self:service}
    ServiceRole: "Backend"
    ProgrammingPlatform: Python
    Owner: "David Deal"
  tags:
    Name: ${self:service}
    stage: ${sls:stage}
    Project: "LFX Security"
    Product: "LFX Security"
    ManagedBy: "Serverless CloudFormation"
    SericeType: "Product"
    Service: ${self:service}
    ServiceRole: "Backend"
    ProgrammingPlatform: Python
    Owner: "David Deal"

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
  # Serverless Finch does s3 uploading. Called with 'sls client deploy'.
  # Also allows bucket removal with 'sls client remove'.
  - serverless-finch
  # To avoid a Code Storage Limit after tons of deploys and revisions - we can prune old versions
  # This plugin allows us to remove/prune the old versions either manually or automatically
  - serverless-prune-plugin

functions:
  lfx-security-ossf-scanner:
    name: lfx-security-ossf-scanner
    handler: main.lambda_handler
    description: "LFX Security OSSF Repository Scanner"
