---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Build and Deploy PROD

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  push:
    tags:
      - v0.*
      - v1.*

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Setup
        run: |
          echo "Node version is: $(node --version)"
          echo "Yarn version is: $(yarn --version)"
          echo "Running top level install..."
          yarn install
      - name: Install Python Dependences
        run: |
          echo "Python version is: $(python --version)"
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::716487311010:role/github-actions-deploy
          aws-region: us-east-2
      - name: Deploy Backend
        run: |
          yarn install
          echo "Deploying backend for stage ${STAGE} in region ${AWS_REGION}"
          SLS_DEBUG=* yarn sls deploy --verbose -s ${STAGE} -r ${AWS_REGION}
        env:
          AWS_REGION: us-east-2
          AUTH0_PLATFORM_URL: ${{ secrets.AUTH0_PLATFORM_URL_PROD }}
          AUTH0_PLATFORM_CLIENT_ID: ${{ secrets.AUTH0_PLATFORM_CLIENT_ID_PROD }}
          AUTH0_PLATFORM_CLIENT_SECRET: ${{ secrets.AUTH0_PLATFORM_CLIENT_SECRET_PROD }}
          AUTH0_PLATFORM_AUDIENCE: ${{ secrets.AUTH0_PLATFORM_AUDIENCE_PROD }}
          STAGE: prod
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} {workflow} {status_message} for repository <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>'
          footer: 'Repository: <{repo_url}|{repo}> | <{workflow_url}|View Workflow>'
          mention_users: 'UH8CHEUQL,UNLDL97LZ'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
